### ISSUE TITLE
1.20.1 Game crashes when I try to climb on the eaves

### ISSUE THREAD

**Issue by kingokksa** [alRex-U/ParCool#322]
I'm not sure if it was caused by Parcool, this is the report before my breakdown
[20:16:25] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.world.level.Level.m_46653_(Level.java:488) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.12.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.12.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.util.LinkedList.checkPositionIndex(LinkedList.java:571) ~[?:?]
	at java.util.LinkedList.listIterator(LinkedList.java:878) ~[?:?]
	at java.util.AbstractList.listIterator(AbstractList.java:313) ~[?:?]
	at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:240) ~[?:?]
	at java.util.Collection.removeIf(Collection.java:581) ~[?:?]
	at com.alrex.parcool.common.action.CancelMarks.cancelSneak(CancelMarks.java:32) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at net.minecraft.client.player.LocalPlayer.handler$lpn000$parcool$onIsShiftKeyDown(LocalPlayer.java:11659) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.player.LocalPlayer.m_6144_(LocalPlayer.java) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.world.entity.Entity.m_20164_(Entity.java:2166) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.world.phys.shapes.EntityCollisionContext.<init>(EntityCollisionContext.java:42) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.world.phys.shapes.CollisionContext.m_82750_(CollisionContext.java:15) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.<init>(ChunkAwareBlockCollisionSweeper.java:75) ~[radium-mc1.20.1-0.12.4+git.26c9d8e.jar%231423!/:?]
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.doesBoxCollideWithBlocks(LithiumEntityCollisions.java:47) ~[radium-mc1.20.1-0.12.4+git.26c9d8e.jar%231423!/:?]
	at net.minecraft.world.level.Level.m_45756_(Level.java:6537) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at com.alrex.parcool.utilities.WorldUtil.getWall(WorldUtil.java:88) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at com.alrex.parcool.utilities.WorldUtil.getWallHeight(WorldUtil.java:188) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at com.alrex.parcool.utilities.WorldUtil.getVaultableStep(WorldUtil.java:107) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at com.alrex.parcool.common.action.impl.Vault.canStart(Vault.java:64) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at com.alrex.parcool.common.action.ActionProcessor.onTick(ActionProcessor.java:94) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at com.alrex.parcool.common.action.__ActionProcessor_onTick_PlayerTickEvent.invoke(.dynamic) ~[ParCool-1.20.1-3.3.0.4.jar%231389!/:3.3.0.4]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920) ~[forge-1.20.1-47.3.12-universal.jar%231595!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:285) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:70) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231590!/:?]
	... 20 more
[20:16:25] [Render thread/INFO]: Redirecting com/alrex/parcool/common/action/impl/HangDown$BarAxis

**Comment by kingokksa** [comment]
emmm Sorry, I have only seen this error twice and may not be able to reproduce or provide a more detailed report. I was trying to climb up a trapdoor at the time and then crashed. I don't think this is a big problem and there is no need to worry about it

**Comment by kingokksa** [comment]
I tried triggering the error again and got a more complete report. I hope it's useful to you
The reason why I reported an error this time is probably like this
![image](https://github.com/user-attachments/assets/7690e5eb-a5e5-43c1-908d-932f7af95c49)

[client.txt](https://github.com/user-attachments/files/17929058/client.txt)
[server.txt](https://github.com/user-attachments/files/17929060/server.txt)

**Comment by alRex-U** [comment]
Thanks, I'll try with it
